# Exploratory Data Analysis

## Import the dataset

In [ ]:
import pandas as pd
import numpy as np


data = pd.read_csv("cancer_b.csv")
data.head()

## Perform Statistical Analysis, Descriptive Analysis, etc.

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         357 non-null    int64
 1   Diagnosis                  357 non-null    str
 2   Radius (mean)              357 non-null    float64
 3   Texture (mean)             357 non-null    float64
 4   Perimeter (mean)           357 non-null    float64
 5   Area (mean)                357 non-null    float64
 6   Smoothness (mean)          357 non-null    float64
 7   Compactness (mean)         357 non-null    float64
 8   Concavity (mean)           357 non-null    float64
 9   Concave points (mean)      357 non-null    float64
 10  Symmetry (mean)            357 non-null    float64
 11  Fractal dimension (mean)   357 non-null    float64
 12  Radius (se)                357 non-null    float64
 13  Texture (se)               357 non-null    float64
 14  Perimeter (se)             357 non-null    float64
 15  Area (se)                  357 non-null    float64
 16  Smoothness (se)            357 non-null    float64
 17  Compactness (se)           357 non-null    float64
 18  Concavity (se)             357 non-null    float64
 19  Concave points (se)        357 non-null    float64
 20  Symmetry (se)              357 non-null    float64
 21  Fractal dimension (se)     357 non-null    float64
 22  Radius (worst)             357 non-null    float64
 23  Texture (worst)            357 non-null    float64
 24  Perimeter (worst)          357 non-null    float64
 25  Area (worst)               357 non-null    float64
 26  Smoothness (worst)         357 non-null    float64
 27  Compactness (worst)        357 non-null    float64
 28  Concavity (worst)          357 non-null    float64
 29  Concave points (worst)     357 non-null    float64
 30  Symmetry (worst)           357 non-null    float64
 31  Fractal dimension (worst)  357 non-null    float64
dtypes: float64(30), int64(1), str(1)
memory usage: 89.7 KB

In [5]:
data.describe()

,Id,Radius (mean),Texture (mean),Perimeter (mean),Area (mean),Smoothness (mean),Compactness (mean),Concavity (mean),Concave points (mean),Symmetry (mean),...,Radius (worst),Texture (worst),Perimeter (worst),Area (worst),Smoothness (worst),Compactness (worst),Concavity (worst),Concave points (worst),Symmetry (worst),Fractal dimension (worst)
count,3.570000e+02,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,...,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000
mean,2.654382e+07,12.146524,17.914762,78.075406,462.790196,0.092478,0.080085,0.046058,0.025717,0.174186,...,13.379801,23.515070,87.005938,558.899440,0.124959,0.182673,0.166238,0.074444,0.270246,0.079442
std,1.167397e+08,1.780512,3.995125,11.807438,134.287118,0.013446,0.033750,0.043442,0.015909,0.024807,...,1.981368,5.493955,13.527091,163.601424,0.020013,0.092180,0.140368,0.035797,0.041745,0.013804
min,8.913000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156600,0.055210
25%,8.746620e+05,11.080000,15.150000,70.870000,378.200000,0.083060,0.055620,0.020310,0.015020,0.158000,...,12.080000,19.580000,78.270000,447.100000,0.110400,0.112000,0.077080,0.051040,0.240600,0.070090
50%,9.089160e+05,12.200000,17.390000,78.180000,458.400000,0.090760,0.075290,0.037090,0.023440,0.171400,...,13.350000,22.820000,86.920000,547.400000,0.125400,0.169800,0.141200,0.074310,0.268700,0.077120
75%,8.812816e+06,13.370000,19.760000,86.100000,551.100000,0.100700,0.097550,0.059990,0.032510,0.189000,...,14.800000,26.510000,96.590000,670.000000,0.137600,0.230200,0.221600,0.097490,0.298300,0.085410
max,9.113205e+08,17.850000,33.810000,114.600000,992.100000,0.163400,0.223900,0.410800,0.085340,0.274300,...,19.820000,41.780000,127.100000,1210.000000,0.200600,0.584900,1.252000,0.175000,0.422800,0.148600

In [6]:
data.isnull().sum()

Id                           0
Diagnosis                    0
Radius (mean)                0
Texture (mean)               0
Perimeter (mean)             0
Area (mean)                  0
Smoothness (mean)            0
Compactness (mean)           0
Concavity (mean)             0
Concave points (mean)        0
Symmetry (mean)              0
Fractal dimension (mean)     0
Radius (se)                  0
Texture (se)                 0
Perimeter (se)               0
Area (se)                    0
Smoothness (se)              0
Compactness (se)             0
Concavity (se)               0
Concave points (se)          0
Symmetry (se)                0
Fractal dimension (se)       0
Radius (worst)               0
Texture (worst)              0
Perimeter (worst)            0
Area (worst)                 0
Smoothness (worst)           0
Compactness (worst)          0
Concavity (worst)            0
Concave points (worst)       0
Symmetry (worst)             0
Fractal dimension (worst)    0
dtype: int64

In [7]:
data.columns

Index(['Id', 'Diagnosis', 'Radius (mean)', 'Texture (mean)',
       'Perimeter (mean)', 'Area (mean)', 'Smoothness (mean)',
       'Compactness (mean)', 'Concavity (mean)', 'Concave points (mean)',
       'Symmetry (mean)', 'Fractal dimension (mean)', 'Radius (se)',
       'Texture (se)', 'Perimeter (se)', 'Area (se)', 'Smoothness (se)',
       'Compactness (se)', 'Concavity (se)', 'Concave points (se)',
       'Symmetry (se)', 'Fractal dimension (se)', 'Radius (worst)',
       'Texture (worst)', 'Perimeter (worst)', 'Area (worst)',
       'Smoothness (worst)', 'Compactness (worst)', 'Concavity (worst)',
       'Concave points (worst)', 'Symmetry (worst)',
       'Fractal dimension (worst)'],
      dtype='str')

In [8]:
data['Id']

0       8510426
1       8510653
2       8510824
3        854941
4      85713702
         ...
352      925277
353      925291
354      925292
355      925311
356       92751
Name: Id, Length: 357, dtype: int64

In [13]:
cleaned_data = data[['Id','Diagnosis','Radius (mean)', 'Area (mean)', 'Smoothness (mean)']]
cleaned_data

           Id Diagnosis  Radius (mean)  Area (mean)  Smoothness (mean)
0     8510426         B         13.540        566.3            0.09779
1     8510653         A         13.080        520.0            0.10750
2     8510824         B          9.504        273.9            0.10240
3      854941         B         13.030        523.8            0.08983
4    85713702         B          8.196        201.9            0.08600
..        ...       ...            ...          ...                ...
352    925277         B         14.590        657.1            0.08473
353    925291         B         11.510        403.5            0.09261
354    925292         B         14.050        600.4            0.09929
355    925311         B         11.200        386.0            0.07449
356     92751         B          7.760        181.0            0.05263

[357 rows x 5 columns]

In [12]:
cleaned_data_by_drop = data.drop(['Area (mean)', 'Smoothness (mean)',
       'Compactness (mean)', 'Concavity (mean)', 'Concave points (mean)',
       'Symmetry (mean)', 'Fractal dimension (mean)', 'Radius (se)',
       'Texture (se)', 'Perimeter (se)', 'Area (se)', 'Smoothness (se)',
       'Compactness (se)', 'Concavity (se)', 'Concave points (se)',
       'Symmetry (se)', 'Fractal dimension (se)', 'Radius (worst)',
       'Texture (worst)', 'Perimeter (worst)', 'Area (worst)',
       'Smoothness (worst)', 'Compactness (worst)', 'Concavity (worst)',
       'Concave points (worst)', 'Symmetry (worst)',
       'Fractal dimension (worst)'], axis = 1)
cleaned_data_by_drop

           Id Diagnosis  Radius (mean)  Texture (mean)  Perimeter (mean)
0     8510426         B         13.540           14.36             87.46
1     8510653         A         13.080           15.71             85.63
2     8510824         B          9.504           12.44             60.34
3      854941         B         13.030           18.42             82.61
4    85713702         B          8.196           16.84             51.71
..        ...       ...            ...             ...               ...
352    925277         B         14.590           22.68             96.39
353    925291         B         11.510           23.93             74.52
354    925292         B         14.050           27.15             91.38
355    925311         B         11.200           29.37             70.67
356     92751         B          7.760           24.54             47.92

[357 rows x 5 columns]

In [14]:
cleaned_data.head()

         Id Diagnosis  Radius (mean)  Area (mean)  Smoothness (mean)
0   8510426         B         13.540        566.3            0.09779
1   8510653         A         13.080        520.0            0.10750
2   8510824         B          9.504        273.9            0.10240
3    854941         B         13.030        523.8            0.08983
4  85713702         B          8.196        201.9            0.08600

In [16]:
cleaned_data['Diagnosis'].unique()

<ArrowStringArray>
['B', 'A']
Length: 2, dtype: str

In [19]:
cleaned_data['Diagnosis'].value_counts()

Diagnosis
B    351
A      6
Name: count, dtype: int64

In [ ]:
Q1 = cleaned_data['Area (mean)'].quantile(0.25)